[tool.black]
line-length = 100
target-version = ["py35", "py36", "py37", "py38"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 100
known_third_party = ["classad", "docopt", "htcondor", "pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
console_output_style = "count"
